# This is a basic workflow to help you get started with Actions

name: Deploy Website

# Controls when the workflow will run
on:
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Install NodeJS
        uses: actions/setup-node@v2-beta
        with:
         node-version: 12
      - name: Install Surge
        run: npm install -g surge
      - name: Run Surge
        run: surge ./ bootcamp2020_task01.surge.sh --token ${{secretS.SURGE_TOKEN}}

      
      
